export const escrowIdrxAbis = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "closedAt",
        type: "uint256",
      },
    ],
    name: "EscrowClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "createdAt",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "receivers",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "EscrowCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      { indexed: false, internalType: "bool", name: "isActive", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "changedAt",
        type: "uint256",
      },
    ],
    name: "EscrowStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newCycleBalance",
        type: "uint256",
      },
    ],
    name: "FundsTopUp",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "depositWallet",
        type: "address",
      },
    ],
    name: "IDRXWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "netAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "hashedAccountNumber",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "transactionHash",
        type: "bytes32",
      },
    ],
    name: "IDRXWithdrawnToFiat",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ReceiverAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newAmount",
        type: "uint256",
      },
    ],
    name: "ReceiverAmountUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "refundAmount",
        type: "uint256",
      },
    ],
    name: "ReceiverRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "claimedAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "remainingVestedAmount",
        type: "uint256",
      },
    ],
    name: "VestingClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalVestedAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "completedAt",
        type: "uint256",
      },
    ],
    name: "VestingCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "vestingStartTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "vestingDuration",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isVestingEnabled",
        type: "bool",
      },
    ],
    name: "VestingConfigured",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "address", name: "_receiver", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "addReceiver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "calculateVestedAmount",
    outputs: [
      { internalType: "uint256", name: "vestedAmount", type: "uint256" },
      { internalType: "uint256", name: "totalVestedAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_escrowId", type: "bytes32" }],
    name: "closeEscrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_tokenAddress", type: "address" },
      { internalType: "address[]", name: "_receivers", type: "address[]" },
      { internalType: "uint256[]", name: "_amounts", type: "uint256[]" },
      { internalType: "uint256", name: "_vestingStartTime", type: "uint256" },
      { internalType: "uint256", name: "_vestingDuration", type: "uint256" },
    ],
    name: "createEscrow",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "escrowRooms",
    outputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      {
        internalType: "uint256",
        name: "totalAllocatedAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDepositedAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalWithdrawnAmount",
        type: "uint256",
      },
      { internalType: "uint256", name: "availableBalance", type: "uint256" },
      { internalType: "uint256", name: "cycleBalance", type: "uint256" },
      { internalType: "uint256", name: "createdAt", type: "uint256" },
      { internalType: "uint256", name: "lastTopUpAt", type: "uint256" },
      { internalType: "uint256", name: "activeReceiverCount", type: "uint256" },
      { internalType: "bool", name: "isActive", type: "bool" },
      { internalType: "uint256", name: "vestingStartTime", type: "uint256" },
      { internalType: "uint256", name: "vestingDuration", type: "uint256" },
      { internalType: "bool", name: "isVestingEnabled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeRecipient",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_receiver", type: "address" }],
    name: "getActiveEscrowsForReceiver",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_sender", type: "address" }],
    name: "getActiveEscrowsForSender",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_escrowId", type: "bytes32" }],
    name: "getCycleBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_escrowId", type: "bytes32" }],
    name: "getEscrowDetails",
    outputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      {
        internalType: "uint256",
        name: "totalAllocatedAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDepositedAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalWithdrawnAmount",
        type: "uint256",
      },
      { internalType: "uint256", name: "availableBalance", type: "uint256" },
      { internalType: "uint256", name: "createdAt", type: "uint256" },
      { internalType: "uint256", name: "lastTopUpAt", type: "uint256" },
      { internalType: "uint256", name: "receiverCount", type: "uint256" },
      { internalType: "uint256", name: "activeReceiverCount", type: "uint256" },
      {
        internalType: "address[]",
        name: "receiverAddresses",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_escrowId", type: "bytes32" }],
    name: "getEscrowReceivers",
    outputs: [
      { internalType: "address[]", name: "receivers", type: "address[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "getReceiverDetails",
    outputs: [
      { internalType: "uint256", name: "currentAllocation", type: "uint256" },
      { internalType: "uint256", name: "withdrawnAmount", type: "uint256" },
      { internalType: "bool", name: "isActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_receiver", type: "address" }],
    name: "getReceiverEscrows",
    outputs: [
      { internalType: "bytes32[]", name: "escrowIds", type: "bytes32[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "getReceiverVestingInfo",
    outputs: [
      { internalType: "uint256", name: "vestedAmount", type: "uint256" },
      { internalType: "uint256", name: "totalVestedAmount", type: "uint256" },
      { internalType: "uint256", name: "availableToClaim", type: "uint256" },
      { internalType: "uint256", name: "vestingProgress", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getUserEscrows",
    outputs: [
      { internalType: "bytes32[]", name: "escrowIds", type: "bytes32[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_escrowId", type: "bytes32" }],
    name: "getVestingInfo",
    outputs: [
      { internalType: "bool", name: "isVestingEnabled", type: "bool" },
      { internalType: "uint256", name: "vestingStartTime", type: "uint256" },
      { internalType: "uint256", name: "vestingDuration", type: "uint256" },
      { internalType: "uint256", name: "vestingEndTime", type: "uint256" },
      { internalType: "uint256", name: "currentTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "getWithdrawableAmount",
    outputs: [
      { internalType: "uint256", name: "withdrawableAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_escrowId", type: "bytes32" }],
    name: "isEscrowActive",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeBps",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "receiverEscrows",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "removeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "topUpFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      {
        internalType: "uint256",
        name: "_newVestingStartTime",
        type: "uint256",
      },
      { internalType: "uint256", name: "_newVestingDuration", type: "uint256" },
      {
        internalType: "uint256[]",
        name: "_receiverAmounts",
        type: "uint256[]",
      },
    ],
    name: "topUpWithNewVesting",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "address", name: "_receiver", type: "address" },
      { internalType: "uint256", name: "_newAmount", type: "uint256" },
    ],
    name: "updateReceiverAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userEscrows",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "withdrawIDRXToCrypto",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_escrowId", type: "bytes32" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "string", name: "_hashedAccountNumber", type: "string" },
    ],
    name: "withdrawIDRXToFiat",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
